import turtle
t=turtle.Turtle()
t.speed(1)
turtle.title=("Heart shape")
screen=turtle.Screen()
screen.bgcolor("black")
t.left(140)
t.color("black")
t.begin_fill()
t.fillcolor("red")
t.forward(180)
t.circle(-90,200)
#t.left(120)
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.hideturtle()
